<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="UTF-8">
<meta name="description" content="sports">
<meta name="keywords" content="sports">
<meta name="author" content="Black Rabbit -Unicorns-">
<title>Sportlethan GO</title>

<link rel="stylesheet" type="text/css" href="css/main.css">
</head>

<body>
<div id="container">
<header>

<!-- navigation links -->

</header>