CREATE TABLE IF NOT EXISTS Map (
  mapID DECIMAL NOT NULL PRIMARY KEY
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS GeoPoint (
  pointID DECIMAL NOT NULL PRIMARY KEY,
  type VARCHAR(50),
  description VARCHAR(300),
  coordinates VARCHAR(30)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS GeoPath (
  pathID DECIMAL NOT NULL PRIMARY KEY,
  type VARCHAR(50),
  description VARCHAR(300),
  vectors VARCHAR(30)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS GeoArea (
  areaID DECIMAL NOT NULL PRIMARY KEY,
  type VARCHAR(50),
  description VARCHAR(300),
  vectors VARCHAR(30)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS Media (
  mediaID DECIMAL NOT NULL PRIMARY KEY,
  type VARCHAR(50),
  description VARCHAR(300),
  URL VARCHAR(50)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS HWEvent (
  HWEventID DECIMAL NOT NULL PRIMARY KEY,
  date Date,
  description VARCHAR(300),
  localisation VARCHAR(50),
  mediaID DECIMAL,
  FOREIGN KEY (mediaID) REFERENCES Media(mediaID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS HWNews (
  HWNewsID DECIMAL NOT NULL PRIMARY KEY,
  date Date,
  name VARCHAR(30),
  text VARCHAR(1000)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS Club (
  clubID DECIMAL NOT NULL PRIMARY KEY,
  name VARCHAR(30),
  description VARCHAR(300),
  clubGenreID DECIMAL,
  eventID DECIMAL,
  mediaID DECIMAL,
  contactInfoID DECIMAL,
  FOREIGN KEY (clubGenreID) REFERENCES ClubGenre(clubGenreID) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (eventID) REFERENCES Event(eventID) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (mediaID) REFERENCES Media(mediaID) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (contactInfoID) REFERENCES ContactInfo(contactInfoID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS ContactInfo (
  contactInfoID DECIMAL NOT NULL PRIMARY KEY,
  name VARCHAR(30),
  adress VARCHAR(50),
  phone VARCHAR(20),
  email VARCHAR(30)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS Calendar (
  eventID DECIMAL NOT NULL PRIMARY KEY,
  clubID DECIMAL NOT NULL PRIMARY KEY,
  FOREIGN KEY (eventID) REFERENCES Event(eventID) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (clubID) REFERENCES Club(clubID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS Event (
  eventID DECIMAL NOT NULL PRIMARY KEY,
  date Date,
  description VARCHAR(300),
  localisation VARCHAR(50)
) ENGINE = MYISAM ;

CREATE TABLE IF NOT EXISTS ClubGenre (
  clubGenreID DECIMAL NOT NULL PRIMARY KEY,
  name VARCHAR(30),
  localisation VARCHAR(50)
) ENGINE = MYISAM

CREATE TABLE IF NOT EXISTS User
  userID DECIMAL NOT NULL PRIMARY KEY,
  displayName VARCHAR(30),
  email VARCHAR(30),
  userName VARCHAR(30),
  password VARCHAR(20),
  levelCode DECIMAL,
  FOREIGN KEY (levelCode) REFERENCES AccessLevel(levelCode) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = MYISAM

CREATE TABLE IF NOT EXISTS AccessLevel (
  levelCode DECIMAL NOT NULL PRIMARY KEY,
  description VARCHAR(300)
) ENGINE = MYISAM

CREATE TABLE `JunctionGeoPoint` (
  mapID DECIMAL NOT NULL PRIMARY KEY,
  pointID DECIMAL NOT NULL PRIMARY KEY,
  FOREIGN KEY (mapID) REFERENCES Map(mapID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (pointID) REFERENCES GeoPoint(pointID) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE = MYISAM ;

CREATE TABLE `JunctionGeoArea` (
  mapID DECIMAL NOT NULL PRIMARY KEY,
  areaID DECIMAL NOT NULL PRIMARY KEY,
  FOREIGN KEY (mapID) REFERENCES Map(mapID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (areaID) REFERENCES GeoArea(areaID) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE = MYISAM ;

CREATE TABLE `JunctionGeoPath` (
  mapID DECIMAL NOT NULL PRIMARY KEY,
  pathID DECIMAL NOT NULL PRIMARY KEY,
  FOREIGN KEY (mapID) REFERENCES Map(mapID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (pathID) REFERENCES GeoPath(pathID) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE = MYISAM ;

CREATE TABLE `JunctionUserClub` (
  userID DECIMAL NOT NULL PRIMARY KEY,
  clubID DECIMAL NOT NULL PRIMARY KEY,
  FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (clubID) REFERENCES Club(clubID) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE = MYISAM ;
